# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfc6f6a22c8cc715f6e9dd5bdf11ef3fd8b608a3ad3b5f7caa781e69c4f314c54d74856edc8829b9c7e97f06b2d6756c7d6e9eba2b133247cae98b0a193740e6

test:
  secret_key_base: 3c46c4f6a2a390c1f916d72894c64944c4252e3ea76c553ec86eba7d1c714ecdb441b33f00eab18cb82060c7ea83f7a3267a4d328a2b1b99c7de48a9c6517a7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
